version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: petize_test_db
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: petize_app
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: petize_app
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "8080:80"

volumes:
  mysql_data: